version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running phase pre_build"
  build:
    commands:
      - echo "Running phase build"
      - echo "Build started with:"
      - echo "CODEBUILD_SOURCE_VERSION=$CODEBUILD_SOURCE_VERSION"
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo Building the java application...
      - mvn clean install -f pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.main -Dsha1=.12345678 -Dsonar.login=$SONARQUBE_TOKEN
  post_build:
    commands:
      - echo "Running phase post_build"
