version: 0.2

env:
  secrets-manager:
    SONARQUBE_TOKEN: "cloudtrain-codebuild-sonarqube:token"

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Install helm"
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Running phase pre_build"
      - echo "Download common configuration files"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/.mvn/settings.xml /root/.m2/settings.xml
  build:
    on-failure: ABORT
    commands:
      - echo "Running phase build"
      - echo Running commit-stage of the build
      - mvn clean install -f pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.main -Dsha1=.${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8} -Dsonar.login=$SONARQUBE_TOKEN
      - echo "Authenticate on EKS"
      - aws eks update-kubeconfig --name eks-eu-west-1-cloudtrain-dev-cloudtrain
      - echo "Running integration-test-stage of the build"
      - mvn clean verify -f pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.main -Dsha1=.${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
  post_build:
    commands:
      - echo "Running phase post_build"

cache:
  paths:
    - "/root/.m2/**/*"